### ISSUE TITLE
Spawn Sphere not showing using any planks

### ISSUE THREAD

**Issue by afarhansib** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#10]
When I put any planks on armor stand, it does not showing spawn sphere. i looked at the code, and it show 
`"v.spawn_show = query.get_equipped_item_name(0) == 'planks';",` 

i tried to change it to `'oak_planks'` and it worked now.

is this because of item id update? shouldn't this pack updated too?

**Comment by RavinMaddHatter** [comment]
I think you are grabbing an old version check releases
