### ISSUE TITLE
Slime Chunk limit

### ISSUE THREAD

**Issue by Creeperuuu** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#12]
Slime Chunk doesn't show up in 10240 blocks away from spawn

forgot to screenshot it :<

Game Version: 1.20.73
Platform: Mobile

**Comment by RavinMaddHatter** [comment]
Yeah. It won't. In 2 years with 10,000+ downloads you are the 2nd person to
complain about that. We have to pick a distance where it stops as the map
is precomputed. And it gets exponentially more work as the radius is
increased.
