### ISSUE TITLE
Capes dissapear when texture pack is enabled

### ISSUE THREAD

**Issue by steelmonkey** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#15]
Just as the title suggest, when the texture pack is enabled all mine craft capes become invisible, is there a fix or work around for this?

**Comment by RavinMaddHatter** [comment]
Nope there isn't... Not without turning off chunk borders and slime chunks

**Comment by steelmonkey** [comment]
Thanks for the response! Could you explain the technical reason for that
I'm curious? Didn't think capes would affect something like that

**Comment by RavinMaddHatter** [comment]
Because the way the capes work is by modifying the player geometry.. The
way this works is by modifying the player Json..I don't have a hook to put
the geometry in without breaking that stuff
