### ISSUE TITLE
Wiki Is outdated with latest release

### ISSUE THREAD

**Issue by 7ooL** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#16]
I'm loving the pack, I find it useful but have noticed the wiki doesn't explain some of the particle/line color meanings. For example the multiple spheres show with planks could use some better explanations. 

I have the wiki bookmarked as a reference and often return to it.

**Comment by RavinMaddHatter** [comment]
The beauty of open source is each person can contribute and fix the
documentation. If you have a way you want it fixed you can click the edit
button edit it and then submit a "pull request" if you do  make changes
that are correct I will then use git hub to pull the changes into the
central package

**Comment by RavinMaddHatter** [comment]
As the reported didn't respond, closing this as wont fix.
