### ISSUE TITLE
Technical Resource Pack breaks Character Creator skins 

### ISSUE THREAD

**Issue by techjoshua** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#18]
Not sure if there is anything that can be done about this on your end, BUT character creator skins all appear as Steve whenever the Technical Resource Pack is enabled.  Possibly related to https://bugs.mojang.com/browse/MCPE-74493

**Comment by RavinMaddHatter** [comment]
I would have to get rid everything that has anything to do with the player

**Comment by SuperLlama88888** [comment]
By setting `min_engine_version` on the client entity file, character creator skins should work.
