### ISSUE TITLE
Alternative chunk line visualization

### ISSUE THREAD

**Issue by reedacartwright** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#5]
Would it be possible to implement a chunk line visualization using the same png techniques as used to display slime chunks, sim distances, and spawning areas?

**Comment by RavinMaddHatter** [comment]
Yes but it would be more laggy. The reason is that this slime thing is only
1 pixel per chunk. It would probably be better for us to just draw chunk
lines in the ticking area

**Comment by reedacartwright** [comment]
I'm thinking a 209x209 image, with 1-pixel = 1-block resolution, but offset so that the "chunk line" covers half the outer ring of blocks in each chunk. That would cover sim6.

145x145 would cover sim 4.

**Comment by RavinMaddHatter** [comment]
I dont think you realize how this works. Right now, the image for the slime chunks is 512 CHUNKS by 512 CHUNKS. To do what you are proposing it would mean the image has to go from 512 pixels square to 8,192 pixel square. That is 1 pixel per block. Minecraft basically dies if you put a 1080x720 picture in as a single texture. This would be catestrophic
