### ISSUE TITLE
Working for Bedrock 1.19?

### ISSUE THREAD

**Issue by charvik12** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#7]
Will there be an update for 1.19?

I recently discovered this resource pack looking for guardian farm spawning spots, but it does not work on my 1.19 bedrock edition.

Thanks for all the hard work!

**Comment by Rayth** [comment]
![image](https://user-images.githubusercontent.com/4260473/189980205-a68cf7e2-4283-4e96-84bd-146aeac7f33f.png)
Worked fine for me. 1.19.22

**Comment by RavinMaddHatter** [comment]
Works in 19 and 20.

Not an issue, incorrect use of ticketing
