### ISSUE TITLE
Snow man aggravate radius. 

### ISSUE THREAD

**Issue by Tjkieff** [RavinMaddHatter/Bedrock-Technical-Resource-Pack#9]
Hey, could you add something that lets you visualize the area that snow golems will be aggressive to hostile mobs, such as like a snowball in an armor stand's hand?

**Comment by RavinMaddHatter** [comment]
That is one I didn't think of. It can be done, but I don't know the
mechanics yet, so research first.

**Comment by Tjkieff** [comment]
OK, thanks!

**Comment by bud-aj29** [comment]
The latest release will include snowman pursuit radius and snowball throwing radius.
